### ISSUE TITLE
use Midori AI Manager with glibc 2.28

### ISSUE THREAD

**Issue by netnut404** [lunamidori5/Midori-AI#12]
I have a machine that must remain for a time glibc 2.28 ( Rocklylinux 8.x ) to be compatible with some other software preexisting on the machine.  This is what occurs if you try to install the AI Manager on Rocky 8.x..

curl -sSL https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/model_installer.sh | sh

[3500081] Error loading Python lib '/tmp/_MEIVh5PmX/libpython3.9.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIVh5PmX/libpython3.9.so.1.0)
 

With that said, is there any way to use the AI Manager with that? (manually seems to work but I really want the manger)

Thanks for your time.

Net Nut

**Comment by lunamidori5** [comment]
@netnut404 We offer the python code raw if that is something you want to try. 
What deb ver would be the nearest or older than that copy of linux?

**Comment by lunamidori5** [comment]
@netnut404 I would love to add support for your Rocklylinux, but I need to know what the nearest / older Deb ver that would be so I can make dockers to do that

**Comment by netnut404** [comment]
rockylinux is forked from centos  so it's rpm based .. anything designed for RHEL 8 generally works on rockylinux 8

**Comment by lunamidori5** [comment]
> rockylinux is forked from centos so it's rpm based .. anything designed for RHEL 8 generally works on rockylinux 8

@netnut404 would you know of a docker image with rockylinux8 (older would be better) and python 3.10 baked in?

**Comment by netnut404** [comment]
I have not seen rocky 8 in a docker iamge..  I have used it in a virtual machine before for testing, but of course I am trying to run this on rockylinux 8 hardware  and what you get when trying to install is..   curl -sSL https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/model_installer.sh | sh

[33114] Error loading Python lib '/tmp/_MEIsPFdgh/libpython3.9.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIsPFdgh/libpython3.9.so.1.0)

**Comment by lunamidori5** [comment]
@netnut404 are you able to use python 3.10 or 3.11 on that type of linux? I am working on a "All other OS installer" and it will need python 3.10 but it will work about the same as the other programs

**Comment by lunamidori5** [comment]
The site has been updated, please check out the install / run info on the "other os" part in the manager page - https://io.midori-ai.xyz/subsystem/manager/
