### ISSUE TITLE
[BUG] Subsystem_manager can't be found

### ISSUE THREAD

**Issue by YorkyPoo** [lunamidori5/Midori-AI#17]
Subsystem_ manager disappears from the folder when installing and it says it cant find it when installing.

**To Reproduce**
I've extracted the model installer windows, opened up the new folder, ran subsystem_manager. A warning pops up saying Smartscreen cannot be found and is not sure if the app is safe to run. I select run anyways. Subsystem_ manager disappears from the folder then it says it cannot find the folder.

**Expected behavior**
The program to install.

**Host Info (please complete the following information):**
 - OS: Windows 11
 - Version not sure
 - Subsystem Manager Version whatever the newest one today is.

**Comment by lunamidori5** [comment]
I will get right on this

**Comment by lunamidori5** [comment]
@YorkyPoo can you please run ``call subsystem_manager.exe`` if it's not there. Please read download it and run it from command line to see what the error is. There was some major changes upstream that caused things to break and I am super sorry and I hope that we can get this issue resolved as soon as possible

**Comment by YorkyPoo** [comment]
@lunamidori5 `C:\Windows\System32>call subsystem_manager.exe
The system cannot execute the specified program.` I have administrator rights, I am In Admin CMD/PS, I don't have an antivirus on, I opened up the properties and allowed everything, I turned off the firewall and I got this 
`C:\Windows\System32>call subsystem_manager.exe 'subsystem_manager.exe' is not recognized as an internal or external command, operable program or batch file.` Quick install says 'system cannot execute'. Manual Instal says `C:\Windows\System32>powershell Expand-Archive subsystem_manager.zip -DestinationPath .
ExpandArchiveHelper : Failed to create file 'C:\Windows\System32\midori_program_ver.txt' while expanding the archive file
'C:\Windows\System32\subsystem_manager.zip' contents as the file 'C:\Windows\System32\midori_program_ver.txt' already exists. Use
the -Force parameter if you want to overwrite the existing directory 'C:\Windows\System32\midori_program_ver.txt' contents when
expanding the archive file.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:397 char:17
+ ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Windows\Syst...program_ver.txt:String) [Write-Error], IOException
    + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper


C:\Windows\System32>subsystem_manager.exe
The system cannot execute the specified program.`

**Comment by lunamidori5** [comment]
Yeah you need to put it in a standard folder not in the windows/system32 directory. It will not run in that ever. Just for people's safety.

**Comment by lunamidori5** [comment]
You can CD over to a different directory and then run the command there and it will work just fine

**Comment by YorkyPoo** [comment]
I will try that when I get back. I thought I did yesterday but then I started using GPT-4 to try to figure work through things.

**Comment by lunamidori5** [comment]
@YorkyPoo just let me know if you can get this working, I also run windows and I just make a folder called "midoriai" on my flash drive. It should work like one of those smaller programs like 7zip or other that you download place in a folder and boom it works. let me know if there are things I can help or fix!

**Comment by YorkyPoo** [comment]
@lunamidori5 'Operation did not complete successfully because the file contains a virus or potentially unwanted software' I've had to act quickly to run it as admin to get that to show up before it would just vanish. I can't find an antivirus on my computer. If I did anything it would have been Panda when I first got it but I cannot find that program anywhere. Imma try to install it on another computer. So it unfolded on my Home PC. After I knock out some homework for Paramedic class ill try to Install Anythingllm Docker and finish the Midori Install on that computer.

**Comment by lunamidori5** [comment]
Thank you for this report! Ill file a report with MS and see if we can get that unflaged. (You can run the file on virustotal / other tools and see that only 1 out of 70 flag it, I think its due to the way we hook into the docker vm layer, but ill be working on a fix)

**Comment by lunamidori5** [comment]
@YorkyPoo I am pushing a fix to the server right now, please make a new folder in your downloads folder (or where ever is not the root of c or a system folder), and then install like normal

**Comment by lunamidori5** [comment]
I am closing this issue, feel free to reopen it if you have more questions or comments <3

**Comment by YorkyPoo** [comment]
Ok thank you, sorry I haven't had more time time to mess with it but I am
hoping I will this weekend.
