### ISSUE TITLE
unexpected exception when launching subsystem.

### ISSUE THREAD

**Issue by marc-2019** [lunamidori5/Midori-AI#19]
**Describe the bug**
On running subsystem to check the version I got this error.

**To Reproduce**
D:\Local AI>subsystem_manager.bat
Could Not Find D:\Local AI\model_installer.zip
Could Not Find D:\Local AI\model_installer.bat
Could Not Find D:\Local AI\model_installer.exe
Could Not Find D:\Local AI\restart.bat
Traceback (most recent call last):
  File "subsystem_manager.py", line 109, in <module>
  File "support.py", line 330, in data_helper_python
FileNotFoundError: [Errno 2] No such file or directory: '192.168.1.54_log_05222024.txt'
[31376] Failed to execute script 'subsystem_manager' due to unhandled exception!

**Host Info (please complete the following information):**
 - OS: Win
 - Version 11
 - Subsystem Manager Version [e.g. 24.2.24.1]

**Additional context**

**Comment by lunamidori5** [comment]
Can you please fill out all relevant information. Did it sell restart. Like tell me what it did. Also please fill out the version and the title. @marc-2019

**Comment by lunamidori5** [comment]
Okay I found the bug, just reinstall from the windows part of the https://io.midori-ai.xyz/subsystem/manager/#install-midori-ai-subsystem-manager and it will work

**Comment by marc-2019** [comment]
is this the part you mean?

D:\Local AI>curl -sSL https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/shell_files/model_installer.bat -o subsystem_manager.bat && subsystem_manager.bat
Could Not Find D:\Local AI\model_installer.zip
Could Not Find D:\Local AI\model_installer.bat
Could Not Find D:\Local AI\model_installer.exe
Could Not Find D:\Local AI\restart.bat
Traceback (most recent call last):
  File "subsystem_manager.py", line 109, in <module>
  File "support.py", line 330, in data_helper_python
FileNotFoundError: [Errno 2] No such file or directory: '192.168.1.54_log_05222024.txt'
[16256] Failed to execute script 'subsystem_manager' due to unhandled exception!
