### ISSUE TITLE
[BUG] missed mounts

### ISSUE THREAD

**Issue by jaburges** [lunamidori5/Midori-AI#20]
**Describe the bug**
Running the Midori Subsystem installer, following the guide the backend install fails of localai

**Screenshots**
![image](https://github.com/lunamidori5/Midori-AI/assets/14154875/49b222a4-db45-4e92-8de3-47e5d49e23a7)

for Unraid the mounts should be:
```
/mnt/user/appdata/Midori/audio
/mnt/user/appdata/Midori/images
/mnt/user/appdata/Midori/models
/mnt/user/appdata/Midori/files
```
**Host Info (please complete the following information):**
 - OS: Unraid using Docker

**Additional context**
```
2024-06-02 05:06:55 (21.3 MB/s) - '.env' saved [3463/3463]
Running mv docker-compose.yaml /app/files/localai/docker-compose.yaml
Running mv .env /app/files/localai/.env
Running docker compose -f ./files/localai/docker-compose.yaml down --rmi all
Running echo "LocalAI GPU is installed and running... Please wait 30mins before using or restarting"
LocalAI GPU is installed and running... Please wait 30mins before using or restarting
Running: docker compose -f ./files/localai/docker-compose.yaml up -d
stat /app/files/localai/docker-compose.yaml: no such file or directory
We are running localai on 38080
Please press enter to go back to the main menu: 
```

**Comment by jaburges** [comment]
To work around this I can start the install of the localai backend (which fails).
BUT the `wget [gpu docker-compose.yaml URL] -O docker-compose.yaml` IS successful
so I can run the command manually
`docker compose -f /app/files/localai/docker-compose.yaml up`

![image](https://github.com/lunamidori5/Midori-AI/assets/14154875/34e8f1ac-4bce-4a54-a39e-2faedbc1e938)

**Comment by lunamidori5** [comment]
@jaburges we are now switching away from docker compose to use our own docker run based API, I would love to have input on how unraid would like its mounts as this remake is underway

**Comment by lunamidori5** [comment]
Closing Issue as it is stale, please reopen if I am wrong
