### ISSUE TITLE
[BUG] Error: No module named 'support'

### ISSUE THREAD

**Issue by edurenye** [lunamidori5/Midori-AI#23]
**Describe the bug**
I just run quick install script:
`curl -sSL https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/shell_files/model_installer.sh > model_installer.sh && bash ./model_installer.sh`

And got the following output:
`Traceback (most recent call last):`
`  File "subsystem_manager.py", line 4, in <module>`
`ModuleNotFoundError: No module named 'support'`
`[290617] Failed to execute script 'subsystem_manager' due to unhandled exception!`

**To Reproduce**
- Run the script
-  Get the error

**Expected behavior**
It should install without errors.

**Host Info (please complete the following information):**
 - OS: Ubuntu
 - Version: 24.04

**Comment by edurenye** [comment]
I get the same result if I use the manual steps.

**Comment by lunamidori5** [comment]
Thank you for this report I'll get right on this @edurenye

**Comment by lunamidori5** [comment]
@edurenye can you please test and see if this update fixed it, please purge the venv for the "other os" if your using it
Never mind, its working for other os but not ubuntu...

**Comment by lunamidori5** [comment]
I tested on Arch Linux and on Other OS, both seem to be working now, can you see if they are @edurenye

**Comment by lunamidori5** [comment]
Issue seems fixed closing for now

**Comment by edurenye** [comment]
Yes, it works fine now, thank you very much!
