### ISSUE TITLE
[FEATURE] Incorporate Fabric from Daniel Miessler into Subsystem

### ISSUE THREAD

**Issue by preyevates** [lunamidori5/Midori-AI#24]
**Is your feature request related to a problem? Please describe.**

Add Daniel Miessler's Fabric AI project into the subsystem: https://github.com/danielmiessler/fabric

**Describe the solution you'd like**

Have the subsystem handle the installation of Fabric and incorporate into the front end interfaces (big-agi, anythingllm, etc)

**Describe alternatives you've considered**

I've installed so many I can't keep track. Luna's subsystem is awesome.

**Additional context**

**Comment by lunamidori5** [comment]
Sure thing we just need to get with their team to make sure its okay

**Comment by lunamidori5** [comment]
@preyevates Checking in

**Comment by lunamidori5** [comment]
Stale Issue
