### ISSUE TITLE
[BUG] AI Subsystem Python Runner missing dependencies

### ISSUE THREAD

**Issue by i-may-have-stepped-in-it** [lunamidori5/Midori-AI#26]
**Describe the bug**
AI Subsystem Python Runner missing dependencies and failing to start

**To Reproduce**
Run python3 ./subsystem_python_runner.py

**Expected behavior**
Subsystem starts

**Screenshots**

**Host Info (please complete the following information):**
 - OS: EndeavorOS
 - Subsystem Manager Version 24.9.9.0

**Additional context**
was able to get running by modifying the runner with the following line:
os.system('temp/bin/pip install scikit-learn xgboost')

Please add to requirements.txt:
scikit-learn 
xgboost

**Comment by lunamidori5** [comment]
Hopefully the commit I just pushed adds the missing things

**Comment by lunamidori5** [comment]
FIXED
